import type { CosmicScene } from "@/types";

export const COSMIC_SCENES: CosmicScene[] = [
  {
    month: 0,
    name: "Orion Nebula",
    particleColor: "#A78BFA",
    particleCount: 2000,
    nebulaColor: "#6D28D9",
    description: "Orion Nebula",
  },
  {
    month: 1,
    name: "Andromeda",
    particleColor: "#60A5FA",
    particleCount: 2500,
    nebulaColor: "#1D4ED8",
    description: "Andromeda Galaxy",
  },
  {
    month: 2,
    name: "Aurora Borealis",
    particleColor: "#34D399",
    particleCount: 1800,
    nebulaColor: "#059669",
    description: "Aurora Borealis",
  },
  {
    month: 3,
    name: "Crab Nebula",
    particleColor: "#F472B6",
    particleCount: 2200,
    nebulaColor: "#BE185D",
    description: "Crab Nebula",
  },
  {
    month: 4,
    name: "Milky Way Core",
    particleColor: "#FCD34D",
    particleCount: 3000,
    nebulaColor: "#D97706",
    description: "Milky Way Core",
  },
  {
    month: 5,
    name: "Eagle Nebula",
    particleColor: "#6EE7B7",
    particleCount: 2000,
    nebulaColor: "#10B981",
    description: "Eagle Nebula",
  },
  {
    month: 6,
    name: "Sombrero Galaxy",
    particleColor: "#F9A8D4",
    particleCount: 1600,
    nebulaColor: "#EC4899",
    description: "Sombrero Galaxy",
  },
  {
    month: 7,
    name: "Leonid Shower",
    particleColor: "#FDE68A",
    particleCount: 2800,
    nebulaColor: "#F59E0B",
    description: "Leonid Meteor Shower",
  },
  {
    month: 8,
    name: "Whirlpool Galaxy",
    particleColor: "#93C5FD",
    particleCount: 2200,
    nebulaColor: "#3B82F6",
    description: "Whirlpool Galaxy",
  },
  {
    month: 9,
    name: "Veil Nebula",
    particleColor: "#C4B5FD",
    particleCount: 1800,
    nebulaColor: "#7C3AED",
    description: "Veil Nebula",
  },
  {
    month: 10,
    name: "Pleiades",
    particleColor: "#BAE6FD",
    particleCount: 1400,
    nebulaColor: "#0284C7",
    description: "Pleiades Cluster",
  },
  {
    month: 11,
    name: "Winter Triangle",
    particleColor: "#FCA5A5",
    particleCount: 2000,
    nebulaColor: "#DC2626",
    description: "Winter Triangle",
  },
];
